### ISSUE TITLE
Add Snips to the resources

### ISSUE THREAD

**Issue by maelp** [voice-engine/make-a-smart-speaker#1]
Hi, it is a very nice resource, perhaps you could also add Snips wakeword engine and ASR engines to the list, we are open-sourcing them over time

You can look at https://snips.ai, you can build your own assistant with the console, download the platform and use it with any audio frontend (beamforming, AEC) that you want, and code any skill that you like

**Comment by xiongyihui** [comment]
@maelp feel free to send a pull request.
